/**
 * Animation cycles measured from the wireframe skeleton asset.
 *
 * GENERATED by `npm run wireframe-cycles` - do not edit by hand. The source
 * of truth is the drawn skeleton in
 * `ai-helper/skills/vector-animations/assets/character-wireframes.svg`: one
 * wireframe per frame, carrying the same assembly group names a character
 * does. Each step below is the change from one skeleton to the next, so the
 * angles are read off drawn poses rather than guessed at.
 *
 * Limb rotations are measured against the spine, so a limb that moved only
 * because the whole figure tipped reads as no joint rotation; the tipping
 * itself is `figureRotate`.
 *
 * Covered: walk (8), run (10), ideal (4), knocked-down (7).
 */

import type { AnimationPoseStep } from './animation.js';

/**
 * walk: measured from `Walk-Animation` in the wireframe asset,
 * 8 frames (0, 1, 2, 3, 4, 5, 6, 7).
 */
export const WALK_CYCLE: readonly AnimationPoseStep[] = [
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': -10, 'back-arm-assembly': 21.1, 'front-leg-assembly': 12.3, 'back-leg-assembly': -13.5 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': -24.1, 'back-arm-assembly': 40.7, 'front-leg-assembly': 15.8, 'back-leg-assembly': -9 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': 18.1, 'back-arm-assembly': -21.9, 'front-leg-assembly': -8.5, 'back-leg-assembly': 4.5 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': 31, 'back-arm-assembly': -0.3, 'front-leg-assembly': -20.2, 'back-leg-assembly': 7.6 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': 18.3, 'back-arm-assembly': -21, 'front-leg-assembly': -8.7, 'back-leg-assembly': 31.2 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': 12.4, 'back-arm-assembly': -35.4, 'front-leg-assembly': -13.1, 'back-leg-assembly': 11.4 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': -16.9, 'back-arm-assembly': 10.4, 'front-leg-assembly': 9.1, 'back-leg-assembly': -13.4 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': -28.9, 'back-arm-assembly': 6.4, 'front-leg-assembly': 13.3, 'back-leg-assembly': -18.9 } },
];

/**
 * run: measured from `Run-Animation` in the wireframe asset,
 * 10 frames (0, 1, 2, 3, 4, 5, 6, 7, 8, 9).
 */
export const RUN_CYCLE: readonly AnimationPoseStep[] = [
  { shiftYPercent: -1.1, rotate: { 'front-arm-assembly': -26.1, 'back-arm-assembly': 43.1, 'front-leg-assembly': 12.3, 'back-leg-assembly': -13.5 } },
  { shiftYPercent: 2.1, figureRotate: 14, rotate: { 'front-arm-assembly': -48.2, 'back-arm-assembly': 18.7, 'front-leg-assembly': 4.1, 'back-leg-assembly': -36.8 } },
  { shiftYPercent: 1.2, figureRotate: -14, rotate: { 'front-arm-assembly': 20, 'back-arm-assembly': -17.4, 'front-leg-assembly': 24.4, 'back-leg-assembly': 35 } },
  { shiftYPercent: 0.5, rotate: { 'front-arm-assembly': 27.6, 'back-arm-assembly': -28.5, 'front-leg-assembly': -9.2, 'back-leg-assembly': 18.7 } },
  { shiftYPercent: -1.3, rotate: { 'front-arm-assembly': 31.8, 'back-arm-assembly': -33.1, 'front-leg-assembly': -40.9, 'back-leg-assembly': 28 } },
  { shiftYPercent: -1.2, figureRotate: 9.3, rotate: { 'front-arm-assembly': 41.3, 'back-arm-assembly': -30.1, 'front-leg-assembly': -26.8, 'back-leg-assembly': 6.9 } },
  { shiftYPercent: 0.9, figureRotate: -9.3, rotate: { 'front-arm-assembly': 13.3, 'back-arm-assembly': -18.9, 'front-leg-assembly': 24.9, 'back-leg-assembly': -4.8 } },
  { shiftYPercent: -0.7, rotate: { 'front-arm-assembly': -15.4, 'back-arm-assembly': 16.3, 'front-leg-assembly': 29.4, 'back-leg-assembly': -32.9 } },
  { shiftYPercent: -0.2, rotate: { 'front-arm-assembly': -31.1, 'back-arm-assembly': 31.3, 'front-leg-assembly': 7.8, 'back-leg-assembly': -26.4 } },
  { shiftYPercent: -0.2, rotate: { 'front-arm-assembly': -13.2, 'back-arm-assembly': 18.6, 'front-leg-assembly': -26, 'back-leg-assembly': 25.9 } },
];

/**
 * ideal: measured from `Ideal_Stance-Animation` in the wireframe asset,
 * 4 frames (0, 1, 3, 4).
 */
export const IDEAL_CYCLE: readonly AnimationPoseStep[] = [
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': 13.2, 'back-arm-assembly': 11.8, 'front-leg-assembly': 2.4 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': -18.4, 'back-arm-assembly': -14.9, 'front-leg-assembly': -2.4, 'back-leg-assembly': -2.4 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': -17.1, 'back-arm-assembly': -10.5, 'front-leg-assembly': -1.6, 'back-leg-assembly': -2.3 } },
  { shiftYPercent: 0, rotate: { 'front-arm-assembly': 22.3, 'back-arm-assembly': 13.6, 'front-leg-assembly': 1.6, 'back-leg-assembly': 4.7 } },
];

/**
 * knocked-down: measured from `Knockdown-Animation` in the wireframe asset,
 * 7 frames (0, 1, 2, 3, 4, 5, 6).
 */
export const KNOCKED_DOWN_CYCLE: readonly AnimationPoseStep[] = [
  { shiftYPercent: 0.3, figureRotate: -13.6, rotate: { 'front-arm-assembly': 10.1, 'front-leg-assembly': 13.6, 'back-leg-assembly': 13.6 } },
  { shiftYPercent: 1.4, figureRotate: 42.2, rotate: { 'front-leg-assembly': -42.2, 'back-leg-assembly': -39.6 } },
  { shiftYPercent: 7.9, figureRotate: -62.8, rotate: { 'front-leg-assembly': 25, 'back-leg-assembly': 15.8 } },
  { shiftYPercent: 14.8, figureRotate: -32.2, rotate: { 'front-arm-assembly': -10.5, 'back-arm-assembly': 8.9, 'front-leg-assembly': 10.6 } },
  { shiftYPercent: 15, figureRotate: -21.5, rotate: { 'front-arm-assembly': -30.4, 'back-arm-assembly': 8.7, 'front-leg-assembly': 13.8, 'back-leg-assembly': -9 } },
  { shiftYPercent: -1.6, rotate: { 'front-arm-assembly': 13 } },
];

/** Measured cycles by animation type, for {@link animationPoseStep}. */
export const MEASURED_CYCLES: Readonly<Record<string, readonly AnimationPoseStep[]>> = {
  'walk': WALK_CYCLE,
  'run': RUN_CYCLE,
  'ideal': IDEAL_CYCLE,
  'knocked-down': KNOCKED_DOWN_CYCLE,
};
